name: Update OpenChamber [main]

on:
  workflow_dispatch:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "32 * * * *"

jobs:
  update-openchamber:
    name: Update OpenChamber
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: "main"

      - name: Check if update is needed
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          .github/update-openchamber.sh --ci --only-check

      - name: Setup Determinate Nix
        if: steps.check.outputs.should_update == 'true'
        uses: DeterminateSystems/determinate-nix-action@main

      - name: Setup Nix Magic Cache
        if: steps.check.outputs.should_update == 'true'
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Setup cachix
        if: steps.check.outputs.should_update == 'true'
        uses: cachix/cachix-action@v17
        with:
          name: x13
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Update version
        id: update
        if: steps.check.outputs.should_update == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          .github/update-openchamber.sh --ci

      - name: Commit changes
        id: commit
        if: steps.check.outputs.should_update == 'true'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "${{ steps.update.outputs.commit_message }}"
          file_pattern: "*"

      - name: Tag release
        if: steps.check.outputs.should_update == 'true'
        run: |
          git tag "v${{ steps.update.outputs.version }}"
          git push origin "v${{ steps.update.outputs.version }}"
    outputs:
      success: ${{ steps.update.outputs.should_update }}

  test-build:
    if: needs.update-openchamber.outputs.success == 'true'
    continue-on-error: false
    name: Test build ${{ matrix.package }} (${{ matrix.system }})
    needs: update-openchamber
    strategy:
      matrix:
        include:
          - system: x86_64-linux
            runner: ubuntu-24.04
            package: openchamber-server
          - system: x86_64-linux
            runner: ubuntu-24.04
            package: openchamber-gui
          - system: aarch64-linux
            runner: ubuntu-24.04-arm
            package: openchamber-server
          - system: aarch64-linux
            runner: ubuntu-24.04-arm
            package: openchamber-gui
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: "main"

      - name: Setup Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@main

      - name: Setup Nix Magic Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Build
        run: nix build ".#${{ matrix.package }}"
